services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "raos@1234"
      MYSQL_DATABASE: "raos_fin"
      MYSQL_USER: "raos_user"
      MYSQL_PASSWORD: "raos@1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "raos_user", "-praos@1234"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
