server:
  port: 8080

spring:
  datasource:
      url: ${APPSETTING_springDatasourceUrl:jdbc:mysql://localhost:3306/raos_fin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      username: ${APPSETTING_springDatasourceUsername:raos_user}
      password: ${APPSETTING_springDatasourcePassword:raos@1234}
      maxPoolSize: 200
      driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
